#!/usr/bin/env python3
"""Generate data/zonemaps.csv — per-zone local asset paths for cow.exe --zone <lsbZoneId>.

Single source of truth, both in-repo:
  probe/altana_zones.csv                 zone name -> ROM map file (AltanaViewer export)
                                         "<table>/<file>,<name>"              = data/roms/ROM/<...>
                                         "<romdir>/<table>/<file>,<name>"     = data/roms/ROM<romdir>/...
  third_party/lsb/data/enums/zone.yaml   LSB ZoneId enum: snake_case name -> id

Path rule verified against known-correct files (Port Jeuno ROM/1/42.DAT, West Sarutabaruta [S]
ROM5/0/15.DAT) and 100% of rows resolve to an existing file on disk. Base-era zones live in the
base ROM dir; expansion romdirs hold era variants when a row carries a romdir prefix.

Known-zone extras (collision mesh / minimap / map-view texture DAT) are overrides below — extend
as assets land. Run:  python tools/gen_zonemaps.py [--write]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ALTANA = ROOT / "probe" / "altana_zones.csv"
YAML = ROOT / "third_party" / "lsb" / "data" / "enums" / "zone.yaml"
OUT = ROOT / "data" / "zonemaps.csv"

# CSV name (normalized) -> yaml key, for names that don't exact-match after normalization.
ALIASES = {
    # e.g. "delkfutttower": "lower_delkfutts_tower",
}


def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def main() -> int:
    write = "--write" in sys.argv

    # 1. altana rows: (csv_name, rompath)
    alt_rows = []
    for line in ALTANA.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("@"):
            continue
        path, _, name = line.partition(",")
        path, name = path.strip(), name.strip()
        segs = path.split("/")
        if len(segs) == 3:
            romdir = "ROM" + segs[0]
            rel = "/".join(segs[1:])
        elif len(segs) == 2:
            romdir, rel = "ROM", path
        else:
            print(f"WARN bad altana path: {line!r}")
            continue
        rompath = f"data/roms/{romdir}/{rel}.DAT"
        if not (ROOT / rompath).is_file():
            print(f"WARN missing file on disk: {rompath} ({name})")
        alt_rows.append((norm(name), name, rompath))

    # 2. zone.yaml values section: yaml_key -> id
    ids = {}
    in_values = False
    for line in YAML.read_text(encoding="utf-8").splitlines():
        if line.startswith("values:"):
            in_values = True
            continue
        if not in_values:
            continue
        m = re.match(r"^  ([a-z0-9_]+):\s+(\d+)", line)
        if m:
            ids[m.group(1)] = int(m.group(2))

    # 3. join
    by_csvnorm = {}
    for n, name, rompath in alt_rows:
        by_csvnorm.setdefault(n, []).append((name, rompath))

    rows, dupes, no_yaml, multi = [], [], [], []
    used_yaml = set()
    for key, zid in sorted(ids.items(), key=lambda kv: kv[1]):
        nkey = norm(key)
        if nkey in by_csvnorm:
            cands = by_csvnorm[nkey]
            used_yaml.add(nkey)
            if len(cands) > 1:
                multi.append((zid, key, [c[0] for c in cands]))
            rows.append((zid, cands[0][1], cands[0][0]))
        elif nkey in ALIASES:
            alias = norm(ALIASES[nkey])
            if alias in by_csvnorm:
                cands = by_csvnorm[alias]
                used_yaml.add(alias)
                rows.append((zid, cands[0][1], key))
            else:
                no_yaml.append(f"{zid} {key} (alias {ALIASES[nkey]} not in altana)")

    for n, name, rompath in alt_rows:
        if norm(name) not in used_yaml and norm(name) not in set(norm(a) for a in ALIASES.values()):
            no_yaml.append(f"{name} (no matching zone.yaml id)")

    # 4. per-zone local assets. ximesh = auto-detected on disk (tools/mzb2ximesh.py --all writes one per zone);
    # minimap/maptex are hand-verified so far — extend as assets land. The filename rule MUST match
    # tools/mzb2ximesh.py's sanitize() + NAME_OVERRIDES.
    XISH = ROOT / "data" / "ximeshes"
    ximesh_override = {95: "West_Sarutabaruta_[S].ximesh"}  # mirrors mzb2ximesh.NAME_OVERRIDES
    extra_minimap = {95: "data/roms/ROM/17/95.DAT", 246: "data/roms/ROM/18/78.DAT"}
    extra_maptex = {246: "data/roms/ROM/1/20.DAT"}

    rows.sort(key=lambda r: r[0])
    out_lines = [
        "# data/zonemaps.csv — generated by tools/gen_zonemaps.py from probe/altana_zones.csv +",
        "# third_party/lsb/data/enums/zone.yaml. Format:",
        "#   lsbZoneId,mapDAT,ximesh,minimap,maptex,name",
    ]
    for zid, rompath, name in rows:
        base = ximesh_override.get(zid) or (re.sub(r"[^A-Za-z0-9\[\]]+", "_", name) + ".ximesh")
        ximesh = f"data/ximeshes/{base}" if (XISH / base).is_file() else ""
        out_lines.append(f"{zid},{rompath},{ximesh},{extra_minimap.get(zid, '')},{extra_maptex.get(zid, '')},{name}")

    if write:
        OUT.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
        print(f"wrote {OUT} ({len(rows)} zones)")
    else:
        sys.stdout.writelines(l + "\n" for l in out_lines[:6])
        print(f"... ({len(rows)} zones total, --write to emit)")

    if multi:
        print("\n== duplicate CSV name for one zone id (first row used):")
        for zid, key, names in multi:
            print(f"  {zid} {key}: {names}")
    print(f"\nunmatched yaml keys / csv rows ({len(no_yaml)}):")
    for s in no_yaml:
        print(" ", s)
    return 0


if __name__ == "__main__":
    sys.exit(main())
